micronaut:
  application:
    name: devhands
  cache:
    redis:
      enabled: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/devhands
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 120000

r2dbc:
  datasources:
    reactive:
      dialect: POSTGRES
      url: r2dbc:pool:postgresql://localhost:5432/devhands
      username: ${PG_USER:postgres}
      password: ${PG_PASSWORD:postgres}

redis:
  uri: redis://localhost:6380
  caches:
    flights:
      expire-after-write: 1h
  pool:
    enabled: false

devhands:
  scheduling:
    enabled: true

